const DAYS=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
const LABELS={lunch:'Almoço',dinner:'Jantar',snack:'Lanche'};
const LEVELS={survival:{label:'Sobrevivência',tip:'Nesta semana, repita preparações sem culpa. O objetivo é alimentar com o menor número possível de decisões.'},maintenance:{label:'Manutenção',tip:'Prepare uma base e reaproveite em outra refeição. Menos louça, menos desperdício e uma semana que funciona.'},advance:{label:'Avanço',tip:'Aproveite o espaço desta semana para adiantar duas bases e guardar porções no freezer para os dias difíceis.'}};
const RECIPES={
survival:[
{n:'Omelete com tomate e pão',i:['ovos','tomate','pão'],c:'Ovos e laticínios'},{n:'Arroz, feijão e ovo',i:['arroz','feijão','ovos'],c:'Mercearia'},{n:'Macarrão rápido com atum',i:['macarrão','atum','molho de tomate'],c:'Mercearia'},{n:'Frango desfiado com arroz',i:['frango','arroz','cenoura'],c:'Carnes'},{n:'Sanduíche quente completo',i:['pão','queijo','tomate'],c:'Padaria'},{n:'Sopa rápida de legumes',i:['batata','cenoura','abobrinha'],c:'Hortifruti'},{n:'Cuscuz com ovos',i:['flocão de milho','ovos','manteiga'],c:'Mercearia'}],
maintenance:[
{n:'Frango assado, arroz e salada',i:['frango','arroz','alface','tomate'],c:'Carnes'},{n:'Carne moída com legumes',i:['carne moída','cenoura','abobrinha','arroz'],c:'Carnes'},{n:'Macarrão à bolonhesa simples',i:['macarrão','carne moída','molho de tomate'],c:'Mercearia'},{n:'Arroz, feijão, bife e couve',i:['arroz','feijão','bife','couve'],c:'Carnes'},{n:'Torta prática de frango',i:['frango','farinha','ovos','leite'],c:'Mercearia'},{n:'Peixe assado com batatas',i:['filé de peixe','batata','limão'],c:'Carnes'},{n:'Risoto simples de legumes',i:['arroz','ervilha','cenoura','queijo'],c:'Mercearia'}],
advance:[
{n:'Frango marinado, cuscuz e legumes',i:['frango','cuscuz marroquino','abobrinha','pimentão'],c:'Carnes'},{n:'Escondidinho de carne e salada',i:['carne moída','mandioca','alface','tomate'],c:'Carnes'},{n:'Peixe ao forno com arroz de brócolis',i:['filé de peixe','arroz','brócolis','limão'],c:'Carnes'},{n:'Lasanha de berinjela',i:['berinjela','carne moída','molho de tomate','queijo'],c:'Hortifruti'},{n:'Frango ao curry suave',i:['frango','leite de coco','curry','arroz'],c:'Carnes'},{n:'Almôndegas, purê e vagem',i:['carne moída','batata','vagem','molho de tomate'],c:'Carnes'},{n:'Quiche de legumes e folhas',i:['farinha','ovos','queijo','legumes','folhas'],c:'Mercearia'}],
snack:[{n:'Fruta com aveia',i:['banana','aveia'],c:'Hortifruti'},{n:'Pão de queijo e fruta',i:['pão de queijo','maçã'],c:'Congelados'},{n:'Iogurte com banana',i:['iogurte','banana'],c:'Laticínios'},{n:'Pão com queijo',i:['pão','queijo'],c:'Padaria'}]};
const emergency=[['Ovos mexidos + pão','Uma panela • cerca de 8 minutos'],['Macarrão com molho pronto','Uma panela • poucos ingredientes'],['Arroz, feijão e ovo','Use porções congeladas, se tiver'],['Sanduíche + fruta','Sem fogão • montagem rápida'],['Refeição pronta do freezer','É para isso que o freezer existe']];
let state=JSON.parse(localStorage.getItem('cardapioPossivel')||'null')||{level:'maintenance',people:4,meals:['lunch','dinner'],restrictions:'',pantry:[],plan:[],favorites:[],checked:[],useFirst:[],freezer:[]};
let selectedDay=0,deferredPrompt;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('cardapioPossivel',JSON.stringify(state))}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));scrollTo(0,0);if(id==='plan')renderPlan();if(id==='shopping')renderShopping();if(id==='organize')renderOrganize();if(id==='impossible')renderEmergency()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function generate(){state.plan=DAYS.map((_,d)=>state.meals.map((type,m)=>{let pool=type==='snack'?RECIPES.snack:RECIPES[state.level];return{...pool[(d+m*2)%pool.length],type,id:`${d}-${type}`}}));state.checked=[];save()}
function renderPlan(){if(!state.plan.length)generate();$('#planLevel').textContent=`NÍVEL ${LEVELS[state.level].label.toUpperCase()}`;$('#weekStrip').innerHTML=DAYS.map((d,i)=>`<button class="day-pill ${i===selectedDay?'active':''}" data-day="${i}"><small>${d}</small><b>${i+1}</b></button>`).join('');$('#dayPlan').innerHTML=state.plan[selectedDay].map(r=>`<article class="meal-card"><div class="meal-top"><small>${LABELS[r.type].toUpperCase()}</small></div><h3>${r.n}</h3><p>${r.i.join(' • ')}</p><div class="meal-actions"><button class="swap" data-id="${r.id}">↻ Trocar</button><button class="favorite ${state.favorites.includes(r.n)?'active':''}" data-name="${r.n}">♡ Favoritar</button></div></article>`).join('');$('#levelTip').innerHTML=`<b>Dica possível:</b> ${LEVELS[state.level].tip}`}
function swap(id){let [d,type]=id.split('-'),current=state.plan[d].find(x=>x.type===type),pool=type==='snack'?RECIPES.snack:RECIPES[state.level],idx=(pool.findIndex(x=>x.n===current.n)+1)%pool.length;Object.assign(current,{...pool[idx],type,id});save();renderPlan();toast('Refeição trocada')}
function shopping(){let owned=new Set(state.pantry.map(x=>x.toLowerCase()));let all=state.plan.flat().flatMap(r=>r.i).filter(x=>!owned.has(x.toLowerCase()));let counts={};all.forEach(x=>counts[x]=(counts[x]||0)+1);let cats={};Object.entries(counts).forEach(([n,q])=>{let c=/frango|carne|bife|peixe|atum/.test(n)?'Carnes e proteínas':/tomate|cenoura|alface|couve|batata|abobrinha|berinjela|brócolis|vagem|banana|maçã|limão|folhas|legumes|mandioca|pimentão/.test(n)?'Hortifruti':/queijo|leite|iogurte|manteiga|ovos/.test(n)?'Frios, ovos e laticínios':/pão/.test(n)?'Padaria':'Mercearia';(cats[c]??=[]).push({n,q})});return cats}
function renderShopping(){let cats=shopping(),items=Object.values(cats).flat(),done=items.filter(x=>state.checked.includes(x.n)).length;$('#shopProgress').style.width=`${items.length?done/items.length*100:0}%`;$('#shoppingList').innerHTML=Object.entries(cats).map(([c,a])=>`<section class="shop-group"><h3>${c}</h3>${a.map(x=>`<label class="shop-item"><input type="checkbox" data-shop="${x.n}" ${state.checked.includes(x.n)?'checked':''}><span>${x.q>1?x.q+'× ':''}${x.n}</span></label>`).join('')}</section>`).join('')||'<p>Sua despensa já cobre o cardápio. Que alívio!</p>'}
function renderOrganize(){$('#useFirstList').innerHTML=state.useFirst.map((x,i)=>`<li><span>${x}</span><button data-remove="useFirst-${i}">×</button></li>`).join('');$('#freezerList').innerHTML=state.freezer.map((x,i)=>`<li><span>${x.name}</span><b>${x.qty} porç.</b><button data-remove="freezer-${i}">×</button></li>`).join('')}
function renderEmergency(){$('#emergencyList').innerHTML=emergency.map(x=>`<div class="emergency-option"><b>${x[0]}</b><small>${x[1]}</small></div>`).join('')}
function textPlan(){return `*Cardápio Possível™ — Nível ${LEVELS[state.level].label}*\n\n`+state.plan.map((day,i)=>`*${DAYS[i]}*\n`+day.map(r=>`${LABELS[r.type]}: ${r.n}`).join('\n')).join('\n\n')+'\n\nSua casa não precisa estar perfeita. Precisa estar possível.'}
function textShopping(){let cats=shopping();return '*Lista de compras — Cardápio Possível™*\n\n'+Object.entries(cats).map(([c,a])=>`*${c}*\n`+a.map(x=>`☐ ${x.q>1?x.q+'× ':''}${x.n}`).join('\n')).join('\n\n')}
function share(text){window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-level]').forEach(b=>b.onclick=()=>{state.level=b.dataset.level;save();go('setup')});$$('[data-count]').forEach(b=>b.onclick=()=>{$('#peopleOut').value=state.people=Math.max(1,Math.min(20,state.people+Number(b.dataset.count)));save()});
$('#setupForm').onsubmit=e=>{e.preventDefault();state.meals=$$('[name=meals]:checked').map(x=>x.value);if(!state.meals.length)return toast('Escolha ao menos uma refeição');state.restrictions=$('#restrictions').value.trim();state.pantry=$('#pantry').value.split(',').map(x=>x.trim()).filter(Boolean);generate();go('plan')};
document.addEventListener('click',e=>{let b=e.target.closest('[data-day]');if(b){selectedDay=+b.dataset.day;renderPlan()}if(e.target.closest('.swap'))swap(e.target.closest('.swap').dataset.id);if(e.target.closest('.favorite')){let n=e.target.closest('.favorite').dataset.name;state.favorites.includes(n)?state.favorites=state.favorites.filter(x=>x!==n):state.favorites.push(n);save();renderPlan()}if(e.target.dataset.shop){state.checked=e.target.checked?[...new Set([...state.checked,e.target.dataset.shop])]:state.checked.filter(x=>x!==e.target.dataset.shop);save();renderShopping()}if(e.target.dataset.remove){let [k,i]=e.target.dataset.remove.split('-');state[k].splice(+i,1);save();renderOrganize()}});
$$('.inline-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();let inputs=[...f.querySelectorAll('input')],name=inputs[0].value.trim();if(!name)return;if(f.dataset.list==='freezer')state.freezer.push({name,qty:+inputs[1].value});else state.useFirst.push(name);inputs[0].value='';save();renderOrganize()});
$('#sharePlan').onclick=()=>share(textPlan());$('#shareShopping').onclick=()=>share(textShopping());
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
$('#peopleOut').value=state.people;$('#restrictions').value=state.restrictions;$('#pantry').value=state.pantry.join(', ');$$('[name=meals]').forEach(x=>x.checked=state.meals.includes(x.value));renderEmergency();
